### ISSUE TITLE
Mountain Car Reward Fn

### ISSUE THREAD

**Issue by pecey** [ataitler/pyRDDLGym#184]
The current definition of mountain car uses `pos'` and `vel'` while the termination criteria uses `pos` and `vel`. Should the reward function should also be using `pos` and `vel` rather than `pos'` and `vel'` to keep things in sync?

**Comment by mike-gimelfarb** [comment]
Hi Pecey, we are sorry for the confusion. 

If I recall correctly, how it works is like this:
1. Given current state, e.g. pos and vel as input, compute pos' and vel' from the CPFs.
2. Set pos <- pos' and vel <- vel' 
3. Then evaluate the termination condition, action precondition and state invariants using (pos, vel) as current state

We had internal discussion where we debated what the right chronology of updating should be, and it seems this is how things have been traditionally done (i.e. the constraints are always calculated using the most recent state/observation available). In fact, using pos'/vel' in constraints should raise an exception. 

I believe this will need to be better documented in the readthedocs, since it is a very subtle point right now.

**Comment by pecey** [comment]
Thank you @mike-gimelfarb for the response. That helps clear it up. I was assuming reward function to be `R(s,a)` rather than `R(s,a,s')` (and I think that all the gym environments that I have seen use `R(s,a)`) but this helps. 

About the termination discussion: I agree. Its just that the meaning would change depending when you map `x <- x'` for a state variable `x`. In the current scenario, for example, if we don't perform Step 3 (Set pos <- pos' and vel <- vel'), then simply reading the RDDL file gave me an impression that the update was happening on the older value of state and not the updated value, which caused the confusion.

I have created a PR with the reward function. It would be great if you could kindly have a look at it and merge it.
