### ISSUE TITLE
Mountain Car not working

### ISSUE THREAD

**Issue by itsmeashutosh43** [ataitler/pyRDDLGym#189]
I tried running the following code, which was solving mountaincar like a month back, but now something seems to be broken and mountain car doesn't reach its goal position. 

`python3 JaxExample.py MountainCar 1 60 1 False`

I would appreciate any help from your side.

**Comment by mike-gimelfarb** [comment]
Hi,
Thanks for pointing this out. We recently added an action cost to the domain, but due to the way a discrete model is approximated, the loss surface appears to become convex and the planner cannot locate the global optimum. We temporarily set the action cost to zero in the instance, so it should work now, but in the future we would like to improve the optimizer to become robust to such problems.
