### ISSUE TITLE
Prost integration

### ISSUE THREAD

**Issue by GMMDMDIDEMS** [ataitler/pyRDDLGym#214]
Is it possible to use Prost as RDDLSimAgent? Is there any documentation on how to do this?

**Comment by ssanner** [comment]
In principle, yes -- Thomas Keller had originally written RDDLSimAgent to allow use of PROST with pyRDDLGym, which was updated by Christian Muise and others in January 2023.  But we lack documentation and testing of RDDLSimAgent given all of the changes to pyRDDLGym since that time... it has been on our TODO list for a while now.  If you or someone else is willing to test this out and provide documentation, we would gladly welcome your contribution!

===

However, if you're willing to work with the version of pyRDDLGym from January 2023, Christian Muise has provided a dockerized integration of PROST and pyRDDLGym that you can find documented here:

* Section 3.1 of [PyRDDLGym tutorial documentation](https://ataitler.github.io/IPPC2023/pyrddlgym_rddl_tutorial.html)

* "Probabilistic Planning" section of Christian Muise's excellent CISC-813 course on [Automated Planning](https://github.com/AI-Planning/modeling-in-pddl/tree/main/exercises/cisc-813)

Christian has provided further helpful comments on his CISC-813 content as follows:

* The [Dockerfile](https://github.com/AI-Planning/modeling-in-pddl/blob/main/exercises/cisc-813/rddl/Dockerfile) we use, which simply brings together both pyRDDLGym and the PROST planner in the same environment along with our scripts.

* The [command](https://github.com/AI-Planning/modeling-in-pddl/blob/main/exercises/cisc-813/rddl/run.py) used to run the pyRDDLGym server.  The time parameter is not redirected to PROST, but rather passed on to the RDDLSimAgent (since all details of time limits in previous competitions were provided by the Competition Server to the Client agent) -- [this line](https://github.com/ataitler/pyRDDLGym/blob/main/pyRDDLGym/Core/Policies/RDDLSimAgent.py#L14) in RDDLSimAgent shows where the time parameter is used.

* The [bash script](https://github.com/AI-Planning/modeling-in-pddl/blob/main/exercises/cisc-813/rddl/run.py) that ties things together. Lines 34 on show how (1) the pyrddl service is invoked; (2) PROST is fired up with the suggested settings (chosen for simplicity and not necessarily top performance); and (3) how the logging details are piped to a file.

**Comment by mike-gimelfarb** [comment]
Docker files and instructions have been added yesterday to pyrddlgym (per the pull request above).
Please find the instructions how to set up PROST: [here](https://pyrddlgym.readthedocs.io/en/latest/prost.html)
Please note, this is still beta and not extensively tested yet on various machines etc. If you are still in need of running prost, please feel free to give this a shot and let us know in case something is broken.
